image:
  repository: mtphotos/mt-photos
  pullPolicy: IfNotPresent
  tag: nodb-1.16.1@sha256:61e43c5fd36f264e31feb1f2262f372fd8c6abe12f94df73b6d246718cdbce65

portal:
  enabled: true

persistence:
  config:
    enabled: true
    mountPath: "/config"
  upload:
    enabled: true
    mountPath: "/upload"