apiVersion: v2
appVersion: "2.9.9"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
deprecated: false
description: Traefik is a flexible reverse proxy and Ingress Provider.
home: https://truecharts.org/charts/enterprise/traefik
icon: https://ghproxy.com/raw.githubusercontent.com/xushier/HD-Icons/main/border-radius/Traefik_B.png
keywords:
  - traefik
  - ingress
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: traefik
sources:
  - https://github.com/truecharts/charts/tree/master/charts/enterprise/traefik
  - https://hub.docker.com/_/traefik
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
  - https://traefik.io/
type: application
version: 16.0.16
annotations:
  truecharts.org/catagories: |
    - network
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
