{{- $values := .Values }}
{{- $namespace := ( printf "ix-%s" .Release.Name ) }}
{{- if or ( not .Values.ingressClass.enabled ) ( and ( .Values.ingressClass.enabled ) ( .Values.ingressClass.isDefaultClass ) ) }}
{{- $namespace = "default" }}
{{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: opencors-chain
  namespace: {{ $namespace }}
spec:
  chain:
    middlewares:
    - name: basic-ratelimit
    - name: opencors-headers
    - name: compress
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: closedcors-chain
  namespace: {{ $namespace }}
spec:
  chain:
    middlewares:
    - name: basic-ratelimit
    - name: closedcors-headers
    - name: compress
