apiVersion: v2
appVersion: "0.21.1155"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 15.0.1
deprecated: false
description: Advanced tool to create your own TrueCharts-based App
home: https://truecharts.org/charts/stable/custom-app
icon: https://cdn.jsdelivr.net/gh/xushier/HD-Icons/border-radius/Docker_registry_B.png
keywords:
  - custom
kubeVersion: ">=1.24.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: custom-app
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/custom-app
type: application
version: 10.0.4
annotations:
  truecharts.org/catagories: |
    - custom
  truecharts.org/SCALE-support: "true"
