image:
  repository: talebook/talebook
  pullPolicy: IfNotPresent
  tag: v3.6.4@sha256:3709292b8dd4c1596af1b47b2e2d960f00b752ffd9aaef3d72ba5bd58c54b16e

portal:
  enabled: true

persistence:
  data:
    enabled: true
    mountPath: "/data"