apiVersion: v2
appVersion: "0.23.0308"
dependencies:
  - name: common
    version: 11.1.3
deprecated: false
icon: https://mtmt.tech/static/app-logo-1c6fd3ff4d6acf787fd93b93a3c123b3.png
keywords:
  - photo
kubeVersion: ">=1.16.0-0"
name: mt-photos
type: application
version: 1.16.3
annotations:
  truecharts.org/catagories: |
    - photo
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
