image:
  repository: fallenbagel/jellyseerr
  tag: 1.5.0@sha256:3ff0d7af326f4e6db4dbe8679284a4230c9fd4205f59ecc9637ecfbdedb473c3
  pullPolicy: IfNotPresent

env:
  PORT: "{{ .Values.service.main.ports.main.port }}"
  # User Defined
  JELLYFIN_TYPE: ""
  LOG_LEVEL: "info"

service:
  main:
    ports:
      main:
        port: 10241

persistence:
  config:
    enabled: true
    mountPath: "/app/config"

portal:
  enabled: true
