image:
  repository: tinymediamanager/tinymediamanager
  tag: 4.3.9.1@sha256:56fa3d23ce5447162246538b92b1e45a9089b62ce2ed0c576b355978570bdd1d
  pullPolicy: IfNotPresent

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  PASSWORD: ""

service:
  main:
    ports:
      main:
        port: 10179
        targetPort: 4000

persistence:
  data:
    enabled: true
    mountPath: "/data"
  media:
    enabled: true
    mountPath: "/media"

portal:
  enabled: true
